### PR TITLE
adding Volatile function types

### PR DESCRIPTION
**Pull request by doomchild**

### CODE REVIEW

**Comment by jbatte47** [comment]
Looks good, but just a couple things:
1. I personally prefer to fly in the face of convention unless it does something for me; in this case putting the TLD in the package name doesn't make it any more unique than it already is, especially since `com.` is the most common package prefix there is, which in my mind makes the package name _less_ unique. Also, if we must use the TLD prefix notion, the official "rules" say to use the "company"'s primary domain name, which maps over to highbar.io for us, meaning it would need to be `io.highbar.function`. My vote however is to go with `highbar.function` since that's just as unique, but that will probably make everyone mad :)
2. The type-level comments need a bit more work; I was thinking something like the following for the interfaces (using `VolatileConsumer` as an example):

> Defines a consumer that checks an exception, making it unsuitable for use with Java 8 Streams.

Then maybe something like this for the actual `Volatile` class:

> Provides wrappers for common volatile methods that make them suitable for use with Java 8 Streams. Standard exceptions are wrapped with `RuntimeException` to remove the check requirement. Use with caution.

Thoughts?

**Comment by doomchild** [comment]
Makes sense to me.  Java namespaces are weird to me anyway, so I'm fine with changing them.  That means the directory structure changes too, right?  Am I crazy, or do I remember that they need to match up with the package name layout?

**Comment by doomchild** [comment]
I think the terminology of the comments needs some tweaking.  In this case, we're not actually "checking" the exceptions, we're explicitly _un_checking them.  Also, the consumer that is defined by the interface _is_ suitable for use with the Streaming API; that's the whole point of having them!  If we're going to be that explicit, I think my preference would be something along the lines of:

> Defines a consumer that wraps all checked exceptions that would prevent the original consumer from being used with Java 8 Streams.

**Comment by jbatte47** [comment]
I'm confused. If a fluent interface checks a general purpose exception, then it's replaceable by lambdas and method pointers that themselves call APIs that check exceptions, without having to wrap every instance of this in a `try` / `catch`. Most Java 8 Streams only accept things like `Consumer<T>` and `Predicate<T>` etc, which _don't_ check exceptions, so we've got `Volatile` to convert to what they want, but we need interfaces that represent what we have (so-called "volatile" code) -- I go over all that to make the difference clear; as pretend consumers of this API we start with code that is a pain to plug into Streams because of the repetitive error handling and the whole why-is-this-component-doing-that-job problem, and the interfaces are interchangeable with that code (by definition, not compatible with Streams) allowing `Volatile` to convert them to their compatible counterparts. Hence my original wording suggestion. Sorry for the `--verbose` flag; It's late and I'm too groggy to be terse and correct at the same time.

**Comment by jbatte47** [comment]
I've submitted a PR to this one with suggested changes; please review and we'll proceed from there. This PR looks good otherwise.

**Comment by doomchild** [comment]
I've got the PR merged and squashed into this one, so we should be good to go.

**Pull request merged**
