### PR TITLE
5: Add Validation Monad

### PR DESCRIPTION
**Pull request by doomchild**

### CODE REVIEW

**Comment by jlmorgan** [comment]
So, I have some opinions about the state of this structure. Take a look at the JavaScript version of it [here](http://jlmorgan.github.io/node-lodash-fantasy/Validation.html). Bear in mind that I intend to make the following changes:
- Update `orElse` and `orElseGet` to work similar to how Java's `Optional` works.
- Add an `ifFailure` method for that works the same as `ifSuccess`, but for the `Failure` type.

Also, it would be nice to see some more static methods for convenience in streams. Tests… tests would also be nice. And documentation. You are more than welcome to port whatever I did in the JS side to here. I'm not sure how similar you want to make them.

**Comment by jbatte47** [comment]
I just pushed up a couple of small tweaks; also, add something like `Closes #5` to the description if you would, that way the ticket closes as soon as we get this upstream.

**Comment by doomchild** [comment]
Don't tell me how to live my life.

**Comment by jbatte47** [comment]
Looks good. Merging.

**Pull request merged**
